### ISSUE TITLE
Assemble_Iter.py: IndexError: list index out of range

### ISSUE THREAD

**Issue by dacolombo** [kiharalab/DeepMainMast#1]
Hi, I have installed DeepMainMast following the instructions on the README, skipping the installation of Rosetta.
I have tested the installation with the command from `single-chain structure modeling (3j9sA)`:

```shell
dmm_full_multithreads.sh -p $DMM_PATH -c 0.3 -o output_1461 -t 1200 -T 600 -C 8 -M 8 -m ./data/1461/emd_1461.mrc -f ./data/1461/emd_1461.fasta  -H
```

Where `$DMM_PATH` is the path to my dmm installation.

I am getting this error when the `Assemble_Iter.py` script is run:

```
Traceback (most recent call last):
  File "/opt/deepmainmast/server_bin//Assemble_Iter.py", line 295, in <module>
    main()
  File "/opt/deepmainmast/server_bin//Assemble_Iter.py", line 247, in main
    data = create_data_model(filename)
  File "/opt/deepmainmast/server_bin//Assemble_Iter.py", line 69, in create_data_model
    Lseq = seq[-1][0] #Length of  sequence
IndexError: list index out of range
```

The program continues after this error, but it ends with:

```
Can not find output_1461/results/FINAL_CA_MODELs//rank1_daq_score_w9.pdb
```

Which I am not sure whether it's related to the first error or not.

Do you have any clues on what I should look for to solve this issue?

**Comment by dacolombo** [comment]
I re-compiled the C packages and the software is now working.

The issue was with `MainmastC_UnetAssembleMtx` erroring and producing an empty output in the file that is used by `Assemble_Iter.py`.

I am closing the issue since it was probably on my side for how the binaries were compiled the first time.

On a side note: would it make sense to add a `set -e` in the `dmm_full_multithreads.sh` script? So that as soon as a step fails, the script is interrupted?
