### ISSUE TITLE
Several missing file errors in multichain attempt

### ISSUE THREAD

**Issue by drichman** [kiharalab/DeepMainMast#2]
Hi Kihara lab, I'm pasting output below that includes several errors. I'm not sure if they are all related and how I should proceed. I can see one of them might be the result of a bug that adds an extra slash in a path:
"ERROR: Warning: can't open file /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//seq.fasta!"

```
drichman@blackbird:~/Programs/DeepMainMast/dmmmultichain$ bash run.sh
DeepMainMast Mulit-chain Starting
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          32
On-line CPU(s) list:             0-31
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           113
Model name:                      AMD Ryzen 9 3950X 16-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     3500.0000
CPU min MHz:                     2200.0000
BogoMIPS:                        6986.90
Virtualization:                  AMD-V
L1d cache:                       512 KiB
L1i cache:                       512 KiB
L2 cache:                        8 MiB
L3 cache:                        64 MiB
NUMA node0 CPU(s):               0-31
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, P
                                 BRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 c
                                 lflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 
                                 constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl 
                                 pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave
                                  avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misa
                                 lignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfct
                                 r_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb s
                                 tibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflu
                                 shopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cq
                                 m_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat np
                                 t lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists 
                                 pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid 
                                 overflow_recov succor smca sme sev sev_es
Tue Jul 25 17:54:37 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:09:00.0  On |                  N/A |
|  0%   48C    P8    24W / 250W |    405MiB / 10985MiB |      5%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  On   | 00000000:0A:00.0 Off |                  N/A |
|  0%   39C    P8     1W / 250W |     10MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1549      G   /usr/lib/xorg/Xorg                102MiB |
|    0   N/A  N/A      2113      G   /usr/lib/xorg/Xorg                218MiB |
|    0   N/A  N/A      2258      G   /usr/bin/gnome-shell               61MiB |
|    1   N/A  N/A      1549      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      2113      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
--2023-07-25 17:54:37--  https://kiharalab.org/emsuites/deepmainmast/dmmbin/partial_thread.static.linuxgccrelease
Resolving kiharalab.org (kiharalab.org)... 128.210.26.20
Connecting to kiharalab.org (kiharalab.org)|128.210.26.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 140235584 (134M)
Saving to: ‘results/partial_thread.static.linuxgccrelease’

results/partial_thread.sta 100%[======================================>] 133.74M  58.3MB/s    in 2.3s    

2023-07-25 17:54:40 (58.3 MB/s) - ‘results/partial_thread.static.linuxgccrelease’ saved [140235584/140235584]

--2023-07-25 17:54:40--  https://kiharalab.org/emsuites/deepmainmast/dmmbin/rosetta_scripts.static.linuxgccrelease
Resolving kiharalab.org (kiharalab.org)... 128.210.26.20
Connecting to kiharalab.org (kiharalab.org)|128.210.26.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 140205506 (134M)
Saving to: ‘results/rosetta_scripts.static.linuxgccrelease’

results/rosetta_scripts.st 100%[======================================>] 133.71M  57.1MB/s    in 2.3s    

2023-07-25 17:54:42 (57.1 MB/s) - ‘results/rosetta_scripts.static.linuxgccrelease’ saved [140205506/140205506]

Traceback (most recent call last):
  File "emap2secplus/main.py", line 16, in <module>
    from data_processing.Resize_Map import Resize_Map
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/emap2secplus/data_processing/Resize_Map.py", line 7, in <module>
    from numba import jit
  File "/home/drichman/.local/lib/python3.8/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/home/drichman/.local/lib/python3.8/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/home/drichman/.local/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
Traceback (most recent call last):
  File "emap2secplus/main.py", line 16, in <module>
    from data_processing.Resize_Map import Resize_Map
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/emap2secplus/data_processing/Resize_Map.py", line 7, in <module>
    from numba import jit
  File "/home/drichman/.local/lib/python3.8/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/home/drichman/.local/lib/python3.8/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/home/drichman/.local/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
Missing....J285 PATH_p0.3Nch1.csv
Missing....J285 PATH_p0.3Nch5.csv
Missing....J285 PATH_p0.3Nch10.csv
Missing....J285 PATH_p0.4Nch1.csv
Missing....J285 PATH_p0.4Nch5.csv
Missing....J285 PATH_p0.4Nch10.csv
Missing....J285 PATH_p0.5Nch1.csv
Missing....J285 PATH_p0.5Nch5.csv
Missing....J285 PATH_p0.5Nch10.csv
Processing Hetero oligomer pipeline
Traceback (most recent call last):
  File "bin/RosettaCM.py", line 188, in <module>
    main()
  File "bin/RosettaCM.py", line 54, in main
    model = PDBParser().get_structure("model",MODEL)[0]
  File "/home/drichman/.local/lib/python3.8/site-packages/Bio/PDB/PDBParser.py", line 85, in get_structure
    with as_handle(file, mode='rU') as handle:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/drichman/.local/lib/python3.8/site-packages/Bio/File.py", line 113, in as_handle
    with open(handleish, mode, **kwargs) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'results/J285/COMBINEi_DMonly.pdb'
rosetta start
Starting
/home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly/
core.init: Checking for fconfig files in pwd and ./rosetta/flags 
core.init: Rosetta version: rosetta.binary.linux.release-188 r188 2018.33+release.7111c54 7111c54c14ba9a53c012a524f8f1438a8e3fb020 https://www.rosettacommons.org 2018-08-14T02:36:37.119534
core.init: command: /home/drichman/Programs/DeepMainMast/dmmmultichain/results/partial_thread.static.linuxgccrelease -database /home/drichman/Programs/DeepMainMast/dmmmultichain/bin/ros_database/ -in::file::fasta /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//seq.fasta -in::file::alignment /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//alignment.txt -in::file::template_pdb /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//1tmpA.pdb -out:path:all /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly/
core.init: 'RNG device' seed mode, using '/dev/urandom', seed=-1800006344 seed_offset=0 real_seed=-1800006344
core.init.random: RandomGenerator:init: Normal mode, seed=-1800006344 RG_type=mt19937

ERROR: Warning: can't open file /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//seq.fasta!
ERROR:: Exit from: src/core/sequence/util.cc line: 172
BACKTRACE:
[0x5ce3528]
[0x43d9ded]
[0x41145f]
[0x61db174]
[0x624ddd]
caught exception 

File: src/core/sequence/util.cc:172
[ ERROR ] UtilityExitException
ERROR: Warning: can't open file /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//seq.fasta!


rosetta next
results/J285/CM_*/S_*
J285
Traceback (most recent call last):
  File "l_ranker.py", line 43, in <module>
    daq_score = get_daq(model_path + "daq")[2]  
  File "l_ranker.py", line 12, in get_daq
    with open(fname) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/J285/CM_DMonly/S_singletgt_0001.daq'

```

**Comment by wang3702** [comment]
Could you please check your numba version? We would suggest the version numba==0.56.3 or numba==0.56.2.
You can simply check by:
```
import numba
print(numba.__version__)
```

**Comment by drichman** [comment]
I was able to reinstall it in a new conda environment and confirmed that the numba version was correct. It seemed to run correctly much further this time, but then gives a similar error. I'm sorry I can't scroll back further in the output than the many repetitions of "no meaningful density ratio, skip it!", then it says:
```
Traceback (most recent call last):
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/emap2secplus/main.py", line 19, in <module>
    detect_map(cur_map_path,model_path,save_path,
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/emap2secplus/predict/detect_map.py", line 64, in detect_map
    detection_protein = unet_detect_protein(map_data, resume_model_path,
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/emap2secplus/predict/unet_detect_protein.py", line 41, in unet_detect_protein
    model = model.cuda()
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
TRYING TO OPEN MAP
map density range: 0.000000 0.821297
HAHA
map hist log percentage 98:  0.62418556
detected mode mapc 1, mapr 2, maps 3
Origin: [0.0, 0.0, 0.0]
results/J285/unet/Input existed
given contour 0.100000
revised contour 0.160209
Traceback (most recent call last):
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/emap2secplus/main.py", line 19, in <module>
    detect_map(cur_map_path,model_path,save_path,
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/emap2secplus/predict/detect_map.py", line 64, in detect_map
    detection_protein = unet_detect_protein(map_data, resume_model_path,
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/emap2secplus/predict/unet_detect_protein.py", line 41, in unet_detect_protein
    model = model.cuda()
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/programs/x86_64-linux/anaconda/2022.10/envs/deepmainmast/lib/python3.9/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Missing....J285 PATH_p0.3Nch1.csv
Missing....J285 PATH_p0.3Nch5.csv
Missing....J285 PATH_p0.3Nch10.csv
Missing....J285 PATH_p0.4Nch1.csv
Missing....J285 PATH_p0.4Nch5.csv
Missing....J285 PATH_p0.4Nch10.csv
Missing....J285 PATH_p0.5Nch1.csv
Missing....J285 PATH_p0.5Nch5.csv
Missing....J285 PATH_p0.5Nch10.csv
Processing Hetero oligomer pipeline
Traceback (most recent call last):
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/bin/RosettaCM.py", line 188, in <module>
    main()
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/bin/RosettaCM.py", line 49, in main
    if os.mkdir(OutPath):
FileExistsError: [Errno 17] File exists: 'results/J285/CM_DMonly'
rosetta start
Starting
/home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly/
core.init: Checking for fconfig files in pwd and ./rosetta/flags 
core.init: Rosetta version: rosetta.binary.linux.release-188 r188 2018.33+release.7111c54 7111c54c14ba9a53c012a524f8f1438a8e3fb020 https://www.rosettacommons.org 2018-08-14T02:36:37.119534
core.init: command: /home/drichman/Programs/DeepMainMast/dmmmultichain/results/partial_thread.static.linuxgccrelease -database /home/drichman/Programs/DeepMainMast/dmmmultichain/bin/ros_database/ -in::file::fasta /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//seq.fasta -in::file::alignment /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//alignment.txt -in::file::template_pdb /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//1tmpA.pdb -out:path:all /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly/
core.init: 'RNG device' seed mode, using '/dev/urandom', seed=505274102 seed_offset=0 real_seed=505274102
core.init.random: RandomGenerator:init: Normal mode, seed=505274102 RG_type=mt19937

ERROR: Warning: can't open file /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//seq.fasta!
ERROR:: Exit from: src/core/sequence/util.cc line: 172
BACKTRACE:
[0x5ce3528]
[0x43d9ded]
[0x41145f]
[0x61db174]
[0x624ddd]
caught exception 

File: src/core/sequence/util.cc:172
[ ERROR ] UtilityExitException
ERROR: Warning: can't open file /home/drichman/Programs/DeepMainMast/dmmmultichain/results/J285/CM_DMonly//seq.fasta!


rosetta next
results/J285/CM_*/S_*
J285
Traceback (most recent call last):
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/l_ranker.py", line 43, in <module>
    daq_score = get_daq(model_path + "daq")[2]  
  File "/home/drichman/Programs/DeepMainMast/dmmmultichain/l_ranker.py", line 12, in get_daq
    with open(fname) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/J285/CM_DMonly/S_singletgt_0001.daq'
```

**Comment by wang3702** [comment]
I think this time the error raised because of torch version did not work with cuda drvier on your GPU. Typically  https://pytorch.org/get-started/locally/ has detailed instructions to find a torch version work on your machines. But glad to know that you have successfully run with our server.
